version: 2
homebrew_casks:

  - name: "gitstatus"

    binaries:
      - "gitstatus"

    url:
      template: "https://github.com/Jleagle/gitstatus/archive/refs/tags/{{ .Tag }}.zip"

    commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"

    directory: "Formula"

    homepage: "https://github.com/Jleagle/gitstatus"

    skip_upload: false

    dependencies:
      - formula: "go"

    uninstall:
      trash:
        - "~/go/bin/gitstatus"

    repository:
      owner: "Jleagle"
      name: "homebrew-gitstatus"
      branch: "main"
      token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"
      pull_request:
        enabled: true
        draft: false

    commit_author:
      name: "goreleaserbot"
      email: "bot@goreleaser.com"
      signing:
        enabled: false
