version: 2
homebrew_casks:
  - name: "gitstatus"
    repository:
      owner: "Jleagle"
      name: "homebrew-gitstatus"
      token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"
      pull_request:
        enabled: false
        draft: false
