#!/bin/sh
# Prints the Homebrew formula for a release. The release workflow commits the
# output to the Jleagle/homebrew-gitstatus tap as Formula/gitstatus.rb, where
# brew compiles it from the tagged source on the user's machine.
#
#   formula.sh <version> <sha256-of-source-tarball> <commit> <date>
set -eu

VERSION="$1"
SHA256="$2"
COMMIT="$3"
DATE="$4"

case "$VERSION" in
  *[!0-9.]*|.*|*.|"") echo "formula.sh: bad version '$VERSION' (expected e.g. 1.2.3)" >&2; exit 1 ;;
esac

cat <<FORMULA
# Generated by homebrew/formula.sh in Jleagle/gitstatus on each release. DO NOT EDIT.
class Gitstatus < Formula
  desc "Status of every git repo under a directory, with optional pulls"
  homepage "https://github.com/Jleagle/gitstatus"
  url "https://github.com/Jleagle/gitstatus/archive/refs/tags/v${VERSION}.tar.gz"
  sha256 "${SHA256}"
  license "MIT"

  livecheck do
    skip "Updated by the release workflow."
  end

  depends_on "go" => :build

  def install
    # The same -X values the goreleaser builds had; std_go_args adds -s -w.
    ldflags = %W[
      -X main.version=#{version}
      -X main.commit=${COMMIT}
      -X main.date=${DATE}
    ]
    system "go", "build", *std_go_args(ldflags:)
  end

  test do
    assert_match "Version: #{version}", shell_output("#{bin}/gitstatus --version 2>&1")
  end
end
FORMULA
